/**
 * Core interface definitions for ReelForge AI v2.0 Phase 5: Multi-Model AI Intelligence Engine.
 *
 * Establishes provider-independent contracts for LLM communication, structured prompt payloads,
 * response normalization, telemetry (tokens, latency, cost), and circuit breaker health tracking.
 */

export type AIProviderId = "gemini" | "openai" | "claude" | "groq" | "openrouter" | "mock" | "deterministic" | "cache" | "ai-cache";

import type { MCPTool, HermesTelemetry, ExecutionContext } from "../hermes/types";
import type { MemoryTelemetry } from "../memory/types";

export interface ImagePayload {
  data: string;
  mimeType: string;
}

export type AIMessageRole = "user" | "assistant" | "tool";

export interface AIToolCall {
  id: string;
  name: string;
  arguments: any;
}

export interface AIToolResult {
  id: string;
  name: string;
  result: string;
}

export interface AIMessage {
  role: AIMessageRole;
  content: string;
  toolCalls?: AIToolCall[];
  toolResult?: AIToolResult;
}
export type AIModelPreference = "fast" | "powerful" | "cost-effective" | "default";

export interface AITelemetryUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

export interface RoutingDecision {
  selectedProvider: AIProviderId;
  score: number;
  matchedCapabilities: string[];
  rejectedProviders: { id: AIProviderId; reason: string }[];
  routingReason: string;
}

export interface ProviderCapability {
  streaming: boolean;
  vision: boolean;
  json: boolean;
  toolCalling: boolean;
  embeddings: boolean;
  contextWindow: number;
  maxOutputTokens: number;
  supportsImages: boolean;
  supportsAudio: boolean;
  supportsThinking: boolean;
  supportsFunctionCalling: boolean;
  supportsStructuredOutput: boolean;
  latency: "ultra-low" | "low" | "medium" | "high";
  reasoning: "low" | "medium" | "high" | "complex";
}

export interface CapabilityCriteria {
  requiresStreaming?: boolean;
  requiresVision?: boolean;
  requiresJson?: boolean;
  requiresToolCalling?: boolean;
  minimumContextWindow?: number;
  latency?: "ultra-low" | "low" | "medium" | "high";
  reasoning?: "low" | "medium" | "high" | "complex";
  costPreference?: "lowest" | "balanced" | "none";
}

export interface AITelemetry {
  telemetryVersion: number;
  requestId?: string;
  correlationId?: string;
  timestamp: string;
  providerId: AIProviderId;
  requestedModel?: string;
  modelUsed: string;
  routingReason?: string;
  selectedScore?: number;
  latencyMs: number;
  timeToFirstTokenMs?: number;
  firstTokenLatencyMs?: number;
  streamDurationMs?: number;
  streamedTokenCount?: number;
  usage?: AITelemetryUsage;
  tokensIn?: number;
  tokensOut?: number;
  costEstimateUsd?: number;
  costMilliCents?: number;
  fallbackUsed?: boolean;
  fallbackDepth?: number;
  retryCount?: number;
  validationPassed?: boolean;
  cacheHit?: boolean;
  reason?: string;
  adaptiveRevisionsCount?: number;
  baseHeuristicScore?: number;
  finalHeuristicScore?: number;
  failedRules?: string[];
  revisionAttempted?: boolean;
  revisionSucceeded?: boolean;
  revisionLatencyMs?: number;
  scoreImprovement?: number;
  revisionRejectedReason?: "NO_IMPROVEMENT" | "BELOW_THRESHOLD" | "REVISION_FAILED" | "REVISION_TIMEOUT" | "ACCEPTED";
  providerQualityBefore?: number;
  providerQualityAfter?: number;
  qualityDelta?: number;
  learningApplied?: boolean;
  learningSkippedReason?: "CACHED_RESPONSE" | "FALLBACK_USED" | "PROVIDER_ERROR" | "MALFORMED_OUTPUT" | "TIMEOUT" | "ADAPTIVE_DISABLED";
  hermesExecutions?: HermesTelemetry[];
  memoryMetrics?: MemoryTelemetry;
}

export interface AIResponse<T> {
  data: T; // Always present. If returning a tool call, this is fallbackData temporarily.
  toolCalls?: AIToolCall[];
  telemetry: AITelemetry;
}

export type AISchemaType =
  | "brand-intelligence"
  | "script-generation"
  | "competitor-discovery"
  | "competitor-analysis"
  | "content-intelligence"
  | "content-dna"
  | "repurpose"
  | "vision-analysis";

/**
 * Provider-independent prompt payload generated by PromptBuilder.
 * Providers receive this exact structure and never build prompts themselves.
 */
export interface AIPromptPayload<T = unknown> {
  systemPrompt: string;
  userPrompt: string;
  schemaType: AISchemaType | string;
  expectedSchemaDescription: string;
  fallbackData: T;
  
  /**
   * Internal routing intent (e.g. 'memory-compression', 'memory-extraction').
   */
  intent?: string;

  /**
   * Used to associate this invocation with a specific conversation thread.
   */
  conversationId?: string;
  compiledResult?: any;
  temperature?: number;
  maxOutputTokens?: number;
  // Hermes & Orchestrator Fields
  capabilities?: any;
  images?: ImagePayload[];
  tools?: MCPTool[];
  conversationHistory?: AIMessage[];
  executionContext?: ExecutionContext; // Added for Hermes permission propagation
}

export interface AIProviderHealthStatus {
  providerId: AIProviderId;
  name: string;
  isAvailable: boolean;
  isHealthy: boolean;
  consecutiveFailures: number;
  lastFailureTime?: string;
  lastSuccessTime?: string;
  circuitState: "closed" | "open" | "half-open";
}

/**
 * Standard contract for all AI Providers (Gemini, OpenAI, Claude, Orchestrator).
 *
 * Each provider:
 *   1. Communicates solely with its own API
 *   2. Receives provider-independent AIPromptPayload
 *   3. Returns normalized AIResponse<T> via ResponseNormalizer
 *   4. Never exposes raw provider JSON/payloads
 */
export interface IAIProvider {
  readonly id: AIProviderId;
  readonly name: string;
  readonly capabilities: ProviderCapability;
  readonly metadata: {
    providerId: AIProviderId;
    defaultModel: string;
    fastModel: string;
    costPer1kInputTokensMilliCents?: number;
    costPer1kOutputTokensMilliCents?: number;
  };

  /**
   * Returns true if the provider is configured with valid credentials/environment variables.
   * In zero-key development/offline modes, live providers return false.
   */
  isAvailable(): boolean;

  /**
   * Executes structured completion against the LLM API, delegating output normalization
   * to ResponseNormalizer.
   */
  generateStructured<T>(payload: AIPromptPayload<T>): Promise<AIResponse<T>>;

  /**
   * Optional streaming support architecture for real-time token generation.
   */
  generateStream?(payload: AIPromptPayload<any>, onChunk: (chunk: string) => void): Promise<string>;
}
