/**
 * Core interface definitions for ReelForge AI v2.0 Phase 5: Multi-Model AI Intelligence Engine.
 *
 * Establishes provider-independent contracts for LLM communication, structured prompt payloads,
 * response normalization, telemetry (tokens, latency, cost), and circuit breaker health tracking.
 */

export type AIProviderId = "gemini" | "openai" | "claude" | "mock" | "deterministic";

export type AIModelPreference = "fast" | "powerful" | "cost-effective" | "default";

export interface AITelemetryUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

export interface AITelemetry {
  providerId: AIProviderId;
  modelUsed: string;
  latencyMs: number;
  usage?: AITelemetryUsage;
  costEstimateUsd?: number;
  fallbackUsed?: boolean;
}

export interface AIResponse<T> {
  data: T;
  telemetry: AITelemetry;
}

/**
 * Provider-independent prompt payload generated by PromptBuilder.
 * Providers receive this exact structure and never build prompts themselves.
 */
export interface AIPromptPayload<T> {
  systemPrompt: string;
  userPrompt: string;
  expectedSchemaDescription: string;
  schemaType: "brand-intelligence" | "script-generation";
  temperature?: number;
  maxOutputTokens?: number;
  fallbackData: T;
}

export interface AIProviderHealthStatus {
  providerId: AIProviderId;
  name: string;
  isAvailable: boolean;
  isHealthy: boolean;
  consecutiveFailures: number;
  lastFailureTime?: string;
  lastSuccessTime?: string;
  circuitState: "closed" | "open" | "half-open";
}

/**
 * Standard contract for all AI Providers (Gemini, OpenAI, Claude, Orchestrator).
 *
 * Each provider:
 *   1. Communicates solely with its own API
 *   2. Receives provider-independent AIPromptPayload
 *   3. Returns normalized AIResponse<T> via ResponseNormalizer
 *   4. Never exposes raw provider JSON/payloads
 */
export interface IAIProvider {
  readonly id: AIProviderId;
  readonly name: string;

  /**
   * Returns true if the provider is configured with valid credentials/environment variables.
   * In zero-key development/offline modes, live providers return false.
   */
  isAvailable(): boolean;

  /**
   * Executes structured completion against the LLM API, delegating output normalization
   * to ResponseNormalizer.
   */
  generateStructured<T>(payload: AIPromptPayload<T>): Promise<AIResponse<T>>;

  /**
   * Optional streaming support architecture for real-time token generation.
   */
  generateStream?(payload: AIPromptPayload<any>, onChunk: (chunk: string) => void): Promise<string>;
}
